"""empty message

Revision ID: 474f2e4510e0
Revises: aa8c58d699cb
Create Date: 2020-12-03 22:52:59.804338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474f2e4510e0'
down_revision = 'aa8c58d699cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pic_url', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'users', ['pic_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pic_url')
    # ### end Alembic commands ###
