"""please work

Revision ID: aa8c58d699cb
Revises: 95488d4c2794
Create Date: 2020-10-28 17:34:37.190320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8c58d699cb'
down_revision = '95488d4c2794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socials',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user', sa.Integer(), nullable=True),
                    sa.Column('follower', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['follower'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socials')
    # ### end Alembic commands ###
